name: Bug Report
description: Report a bug or unexpected behavior in `Agents-Packages` or any package included in this collection.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report — Agents-Packages
        Please fill out this form to help us identify and fix the issue. When possible, include the package name (e.g. `midori-ai-agent-base`) and path.

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe the bug, and mention which package it affects.
      placeholder: What happened? (include package name)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug. Include commands, package path, and minimal repro if possible.
      placeholder: 1. git clone ... 2. cd package/ 3. run ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the correct behavior.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages and stack traces where available.
      placeholder: Describe what went wrong.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python/node version, package version (if applicable), and any other relevant info.
      placeholder: e.g. Ubuntu 22.04, Python 3.11, `midori-ai-agent-base` v0.1.2
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Paste logs, error messages, or attach screenshots and failure traces if possible.
      placeholder: Drag and drop files or paste logs here.
    validations:
      required: false
