name: Agents-Packages Feedback
description: Share suggestions, ideas, or general feedback about the `Agents-Packages` collection in the `Carly-AGI` monorepo.
labels: [feedback, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for using `Agents-Packages`!
        Please use this form to provide feedback, suggestions, or ideas for improvement related to the packages in this repository.

  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Which package or area does your feedback relate to? (e.g. `midori-ai-agent-base`, logging, docs)
      placeholder: Share your thoughts here, including package name and path if applicable.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of Feedback
      description: Which part of the packages does your feedback relate to?
      options:
        - Documentation
        - Functionality
        - Packaging / Distribution
        - Tests
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: Any logs, repro steps, or extra context (include commands, package name, and file paths).
      placeholder: Paste logs, file paths, or additional context here.
    validations:
      required: false
